# Generated by Django 5.2 on 2025-04-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiorecord",
            name="age",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="audiorecord",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
