# Generated by Django 5.2 on 2025-04-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_app", "0002_audiorecord_age_audiorecord_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiorecord",
            name="transcription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
