# Generated by Django 5.2 on 2025-05-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_app", "0003_audiorecord_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiorecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("unprocessed", "미전사"),
                    ("processing", "처리 중"),
                    ("completed", "전사 완료"),
                    ("failed", "실패"),
                ],
                default="unprocessed",
                max_length=20,
            ),
        ),
    ]
