# Generated by Django 4.2.22 on 2025-07-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0004_audiorecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='category',
            field=models.CharField(choices=[('child', '아동'), ('senior', '노인'), ('atypical', '음성 장애'), ('normal', '일반')], default='normal', max_length=20),
        ),
    ]
