# Generated by Django 4.2.22 on 2025-07-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0005_audiorecord_category'),
    ]

    operations = [
    ]
