# Generated by Django 4.2.22 on 2025-07-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0006_auto_20250704_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='snr_max',
            field=models.FloatField(blank=True, help_text='최대 SNR 값', null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='snr_mean',
            field=models.FloatField(blank=True, help_text='평균 SNR 값', null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='snr_min',
            field=models.FloatField(blank=True, help_text='최소 SNR 값', null=True),
        ),
    ]
