# Generated by Django 4.2.22 on 2025-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0007_audiorecord_snr_max_audiorecord_snr_mean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='alignment_data',
            field=models.JSONField(blank=True, help_text='WhisperX alignment 결과 JSON', null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='alignment_status',
            field=models.CharField(choices=[('unprocessed', '미처리'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='unprocessed', max_length=20),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='category',
            field=models.CharField(choices=[('child', '아동'), ('senior', '노인'), ('atypical', '음성 장애'), ('auditory', '청각 장애'), ('normal', '일반')], default='normal', max_length=20),
        ),
    ]
