# Generated by Django 4.2.22 on 2025-07-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0008_audiorecord_alignment_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiorecord',
            options={'ordering': ['-created_at'], 'verbose_name': '음성 레코드', 'verbose_name_plural': '음성 레코드들'},
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='birth_day',
            field=models.CharField(blank=True, help_text='출생일', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='birth_month',
            field=models.CharField(blank=True, help_text='출생월', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='birth_year',
            field=models.CharField(blank=True, help_text='출생년도', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='category_specific_data',
            field=models.JSONField(blank=True, default=dict, help_text='카테고리별 특화 데이터'),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='data_source',
            field=models.CharField(choices=[('mobile_app', '모바일 앱'), ('django_admin', 'Django 관리자'), ('api_upload', 'API 업로드')], default='mobile_app', max_length=20),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='device_type',
            field=models.CharField(blank=True, help_text='녹음 기기', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='diagnosis',
            field=models.CharField(blank=True, help_text='진단명', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='has_microphone',
            field=models.CharField(blank=True, help_text='마이크 유무', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='name',
            field=models.CharField(blank=True, help_text='이름', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='noise_level',
            field=models.CharField(blank=True, help_text='소음 상태', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='recording_location',
            field=models.CharField(blank=True, help_text='녹음 장소', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='age',
            field=models.CharField(blank=True, help_text='계산된 나이', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='gender',
            field=models.CharField(blank=True, help_text='성별', max_length=10, null=True),
        ),
    ]
