# Generated by Django 4.2.24 on 2025-09-11 04:20

from django.db import migrations, models
import voice_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0009_alter_audiorecord_options_audiorecord_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecord',
            name='audio_file',
            field=models.FileField(upload_to=voice_app.models.category_upload_path),
        ),
    ]
