# Generated by Django 4.2.24 on 2025-10-10 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0010_alter_audiorecord_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='identifier',
            field=models.CharField(blank=True, help_text='C, S, 혹은 A로 시작하고 5자리 숫자로 구성된 식별자', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Identifier는 C, S, 혹은 A로 시작하고 5자리 숫자가 뒤따라야 합니다.', regex='^[CSA]\\d{5}$')]),
        ),
    ]
