# Generated by Django 4.2.24 on 2025-10-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0011_audiorecord_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='age_in_months',
            field=models.IntegerField(blank=True, help_text='나이(개월) (Child/Auditory)', null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='education_level',
            field=models.IntegerField(blank=True, db_index=True, help_text='총 교육년수 (Senior/Auditory)', null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='hearing_level',
            field=models.CharField(blank=True, db_index=True, help_text='청력 수준 (Auditory)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='region',
            field=models.CharField(blank=True, db_index=True, help_text='거주 지역', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='diagnosis',
            field=models.CharField(blank=True, help_text='진단명', max_length=100, null=True),
        ),
    ]
