# Generated by Django 4.2.24 on 2025-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0012_audiorecord_age_in_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='manual_transcription',
            field=models.TextField(blank=True, help_text='수동 수정된 전사 내용', null=True),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='transcription',
            field=models.TextField(blank=True, help_text='Whisper 자동 전사 결과', null=True),
        ),
    ]
