# Generated by Django 4.2.24 on 2025-10-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0013_audiorecord_manual_transcription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecord',
            old_name='manual_transcription',
            new_name='manual_transcript',
        ),
        migrations.RenameField(
            model_name='audiorecord',
            old_name='transcription',
            new_name='transcript',
        ),
    ]
