# Generated by Django 4.2.24 on 2025-10-11 10:16

from django.db import migrations


def copy_transcript_to_manual(apps, schema_editor):
    """transcript 값을 manual_transcript로 복사 (manual_transcript가 비어있는 경우에만)"""
    AudioRecord = apps.get_model('voice_app', 'AudioRecord')
    
    # transcript는 있지만 manual_transcript가 없는 레코드들
    records = AudioRecord.objects.filter(
        transcript__isnull=False
    ).filter(
        manual_transcript__isnull=True
    ) | AudioRecord.objects.filter(
        transcript__isnull=False
    ).filter(
        manual_transcript=''
    )
    
    count = 0
    for record in records:
        if record.transcript:
            record.manual_transcript = record.transcript
            record.save(update_fields=['manual_transcript'])
            count += 1
    
    print(f"[Migration] Copied transcript to manual_transcript for {count} records")


def reverse_copy(apps, schema_editor):
    """역방향 마이그레이션 시 manual_transcript를 비움"""
    AudioRecord = apps.get_model('voice_app', 'AudioRecord')
    AudioRecord.objects.update(manual_transcript=None)
    print("[Migration] Cleared manual_transcript for all records")


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0014_rename_transcription_fields'),
    ]

    operations = [
        migrations.RunPython(copy_transcript_to_manual, reverse_copy),
    ]
