# Generated by Django 4.2.24 on 2025-11-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0015_copy_transcript_to_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='diarization_data',
            field=models.JSONField(blank=True, help_text='화자 분리(diarization) 결과 JSON', null=True),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='diarization_status',
            field=models.CharField(choices=[('unprocessed', '미처리'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='unprocessed', max_length=20),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='num_speakers',
            field=models.IntegerField(blank=True, help_text='감지된 화자 수', null=True),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='category',
            field=models.CharField(choices=[('child', '아동'), ('senior', '성인'), ('atypical', '음성 장애'), ('auditory', '청각 장애'), ('normal', '일반')], default='normal', max_length=20),
        ),
    ]
