# Generated by Django 4.2.24 on 2025-12-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0016_audiorecord_diarization_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='memo',
            field=models.TextField(blank=True, help_text='전사 수정 중 메모', null=True),
        ),
    ]
